### ISSUE TITLE
组件没有处理“焦点逃逸”

### ISSUE THREAD

**Issue by ThaddeusJiang** [pengpengzx/searchInput#1]
如图：
焦点逃离了第一个 Input，进入了第二个 Input。
理想的 select input 应该可以阻止这种现象。

![CleanShot 2021-12-01 at 16 21 17](https://user-images.githubusercontent.com/17308201/144189589-5103831f-7f41-4b79-aa4e-2738f1b8edba.gif)

**Comment by pengpengzx** [comment]
fixed 
获取item限定在当前组件dom下获取
