### ISSUE TITLE
通常含有 search 的 select 组件为了防止频繁触发 API 请求，需要一定处理。

### ISSUE THREAD

**Issue by ThaddeusJiang** [pengpengzx/searchInput#2]
如图

出发 search 的时机稍微欠佳

![CleanShot 2021-12-01 at 16 25 44](https://user-images.githubusercontent.com/17308201/144190080-4f51e40f-dc48-48c0-98d3-cd7d0820271c.gif)

**Comment by pengpengzx** [comment]
fixed
